### ISSUE TITLE
Typing mistakes in code + missing dialog in VS

### ISSUE THREAD

**Issue by nielsenvancura** [MicrosoftDocs/xamarin-docs.cs-cz#2]
1) class is called - "name the new file PhoneTranslator", but inside class you have "public static class PhonewordTranslator"
2) I am at Mac with Visual Studio Community 7.8.2 - can not find Project Option dialog as stated in "After all the icons are copi ..", only Project - Solution Option where "Android aplication" is missing

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: Rychlý start - Xamarin](https://docs.microsoft.com/cs-cz/xamarin/android/get-started/hello-android/hello-android-quickstart?pivots=macos#feedback)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.cs-CZ/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
1. Thanks for your feedback. The filename does seem confusing, since the class name won't match the documentation. The sample code has the same filename, so we'll need to update both the sample & the doc, but we will update it.

2. This does not refer to the **Project** menu, you must "open the **Project Options** dialog by right clicking on the project in the **Solution Pad**". If you right-click on your Android project node in the solution, you will see the **Project Options** dialog.

**Comment by CeciAc** [comment]
Thanks for stepping in, @conceptdev 
I'm moving this issue to the en-us repo. 
You can follow up from there

Kind regards,

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #1470](https://github.com/MicrosoftDocs/xamarin-docs/issues/1470) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @nielsenvancura 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/xamarin-docs/issues/1470

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by nielsenvancura** [comment]
Hi
To addd 2 – this is what i see – no Project Options but Options, here no android


Josef
